server:
  port: 8005
spring:
  datasource:
    url: jdbc:mysql://seoul-arm.zhangjin.tk:13306/boot?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: boot
    password: boot
